### ISSUE TITLE
stereo example?

### ISSUE THREAD

**Issue by bh90210** [go-audio/generator#1]
hi @mattetti 

I've started toying around with an implementation of `go-audio/audio` & `go-audio/generator` but I can not figure out how to produce stereo output on either real-time or offline example. 

It seems the whole project has not moved for a couple of years but any pointers/help are very welcome.

**Comment by mattetti** [comment]
Hey @bh90210, you are right, there is a bug in `func (o *Osc) Fill(buf *audio.FloatBuffer) error ` where the buffer doesn't get properly populated for stereo buffers. The end results is a file with only half of the signal available and at twice the expected frequency. I'll fix that shortly.

**Comment by mattetti** [comment]
So here is the example to produce a stereo output: https://github.com/go-audio/generator/blob/master/examples/offline/stereo/main.go

you can run the program using `go run main.go` or pass argument. The problem was a simple indexing problem when filling up the buffer using the generator: https://github.com/go-audio/generator/commit/fe5438877d8c9150aeda56c0b2990670110efc70#diff-74fe825dbc701700fc5d3b8bb4e40c46R84

I hope this helps. Feel free to reopen the issue if you are still seeing issues.

**Comment by bh90210** [comment]
> Hey @bh90210, you are right, there is a bug in `func (o *Osc) Fill(buf *audio.FloatBuffer) error ` where the buffer doesn't get properly populated for stereo buffers. The end results is a file with only half of the signal available and at twice the expected frequency.

yeap, this is what was happening :)

thanks a lot for the fast reply and help! I will check it out asap.
